language: node_js
notifications:
  slack:
    secure: ACRRyOWAncN1bbqUzxJ7+LpV9lFYJqxg3Vv9ZdTwrYlqegW/Fx6Ch5XOhjNu8GnjDy4AZQQExSXDahBKlcw4b54oZ6UxDGrMjj19qfkBS2v+dVPoPG/6NMT+llYr2RjuA7kX77OQ6KE8MKl3kr02YfIScqxEEzrYej902OJFhFpHymps2TIPvKDeBNemzKg1EwhZDUWxSWE0EX05feFcusfFa+mgBbD0aeiHSICA3b+ntK48+eJyEKiEZGhpBuAXElSbluBeLCeHphZb5azoWP4D+iyBSFDNBJSzxbqVp+/naBkW4wnODuJMeuwIT6oFgZhccp0cbeY3nx+FVPY6TM4ixImmjlHChA4HHtYEKgO2SOjeAwen8SKTjwhbnlzKh8gV6CL6X4hkOhO/LzpgHg8JjqIc2LClVP6LMRpfR8mXvDAH4ZTAGuENBT+3WYeEUSVaiuxryBoOAOHczB+Mgc7DmlrAtYR1Qd/QH6A1UljB3BSrBYrSRVDOPlOGHQ9NcqbNJNSwIzAeej0cHeImsc8CrjK4b+u/fml5RXo2SyV8Mmu0IG4bgTihNKnp9WOHrejZDldEe2FxX3KbzciDR2byZNvoSrVa3PK9oYd4b9ald48UW9gcrwRbocJr6O9NZ8yK++IvZv8dqWtAscadGUoVsty/i2petXhTPOxybig=
    on_success: always
    on_failure: always
